### ISSUE TITLE
Can provide a file download method?

### ISSUE THREAD

**Issue by hiscaler** [yiisoft/data-response#73]
Like https://github.com/yiisoft/yii2/blob/95b0e6010e3960be4e206f9c89c2a4ae5092b86b/framework/web/Response.php

Support send method for download

**Comment by samdark** [comment]
This package is not for a general response but a response with formatted data. For a general file response there's currently nothing so I've put together some code: https://gist.github.com/samdark/e673a2c5de2bfc556e4b6b1e46f028cf

We'll think about where to put this code.

**Comment by hiscaler** [comment]
Thank you very much.

**Comment by samdark** [comment]
https://github.com/yiisoft/response-download/pull/1
